### ISSUE TITLE
Good values for vehicle movement need to be determined

### ISSUE THREAD

**Issue by Zennoe** [Zennoe/leJOS_NXT_programs#14]
These values have to be included into the code to ensure a smooth execution of the code.

**Comment by Zenneo** [comment]
speed = 125
acceleration = 600

**Comment by Zennoe** [comment]
Same as #15 
Motors stall during loading phase

**Comment by Zennoe** [comment]
Fixed for now through 22e23eeac11821045eaeee15a287273a35068e8d
