### ISSUE TITLE
Good values for arm movement need to be determined

### ISSUE THREAD

**Issue by Zennoe** [Zennoe/leJOS_NXT_programs#15]
Variables have to be edited according to these values.

**Comment by Zenneo** [comment]
During initialisation:
Stall error 1, Stall time 25ms works great and doesn't apply too much force. (not tested with actual arm)

**Comment by Zenneo** [comment]
Actual arm_rotate: Speed: 75, Acceleration: 200, Stall error: 2, Stall time: 50

Please note! Due to gear transmission, 90° motor rotation != 90° arm rotation

**Comment by Zenneo** [comment]
Our perfect values:

-- Großer Kontrollarm --

Speed: 60 Accel:300

Ausgangswinkel: 180
Fahrposition: 66°
Abladeposition: -24°

Unterschiede im Winkel:

Ausgangswinkel:0°
Fahrposition: -114°
Abladeposition: -90°

-- Kleiner Seilzug --

Speed: 75 Accel: 200
Stall wenn Winkel größer wird

Ausgangswinkel unten: 368°
Maximalwinkel oben: -702°

Unterschiede im Winkel:

Ausgangswinkel: 0°
Maximalwinkel: -1070°

**Comment by Zenneo** [comment]
Nope not done yet...

**Comment by Zenneo** [comment]
New values:
-- Great control arm --
Speed: 30
Acceleration: 500
Stalled_error: 2
Stalled_time: 150

-- Small winch traction --
Speed: 45
Acceleration: 600
Stalled_error: 3
Stalled_time: 200

**Comment by Zennoe** [comment]
Motors stall during loading phase. Values for unloading phase should be determined as well.

**Comment by Zennoe** [comment]
Fixed for now through 22e23eeac11821045eaeee15a287273a35068e8d

**Comment by Zennoe** [comment]
Current values:

engine_rot_loading_stalled_error = 3
engine_rot_loading_stalled_time = 750
engine_arm_loading_stalled_error = 2
engine_arm_loading_stalled_time = 750

engine_rot_unloading_stalled_error = 5
engine_rot_unloading_stalled_time = 750
engine_arm_unloading_stalled_error = 6
engine_arm_unloading_stalled_time = 750
